name: test

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
  push:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  test-Desktop-build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "stable" # stable
          override: true
      - name: build Desktop
        working-directory: 正常系统端
        run: |
          cargo build --release
  test-pe-build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "stable" # stable
          override: true
      - name: build pe
        working-directory: PE端
        run: |
          cargo build --release
