name: test

on:
  pull_request:
    paths-ignore:
      - '**/README.md'
  push:
  workflow_dispatch:
permissions:
  contents: read

jobs:
  test-Desktop-build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "stable" # stable
          override: true
      - name: build Desktop
        working-directory: 正常系统端
        run: |
          cargo build --release --all-features --target=x86_64-pc-windows-msvc
      - name: Upload Desktop artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LetRecovery-Desktop
          path: 正常系统端/target/x86_64-pc-windows-msvc/release/LetRecovery.exe
          retention-days: 30
  test-pe-build:
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: "stable" # stable
          override: true
      - name: build pe
        working-directory: PE端
        run: |
          cargo build --release --all-features --target=x86_64-pc-windows-msvc
      - name: Upload PE artifacts
        uses: actions/upload-artifact@v4
        with:
          name: LetRecovery-PE
          path: PE端/target/x86_64-pc-windows-msvc/release/LetRecovery.exe
          retention-days: 30
